# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
opt_out_usage
default_platform(:android)

  platform :android do

    desc "Run tests and build all flavors"
    lane :full_pipeline do
      test
      buildAllFalvors
    end


    desc "Runs all the tests"
    lane :test do
      gradle(task: "test")
    end

    desc "Build all flavors"
  lane :buildAllFalvors do
    gradle(
      task: 'assemble',
      build_type: 'debug',
      flavor: 'free'
    )
    gradle(
      task: 'assemble',
      build_type: 'debug',
      flavor: 'full'
    )
  end
end